"""مديول -1 — generic entity generated by ``startmodule``."""

from django.db import models

from apps.core.models import BaseModel


class Module1Item(BaseModel):
    """A minimal CRUD entity for the مديول -1 module.

    Extend with your own domain fields. ``BaseModel`` already provides
    timestamps, created_by/updated_by and is_active.
    """

    name = models.CharField(max_length=255, verbose_name="الاسم")
    code = models.CharField(
        max_length=100, unique=True, verbose_name="الكود",
        help_text="كود فريد يستخدم كمعرّف مرجعي",
    )
    description = models.TextField(blank=True, default="", verbose_name="الوصف")
    quantity = models.PositiveIntegerField(default=0, verbose_name="الكمية")
    sort_order = models.IntegerField(default=0, verbose_name="ترتيب الفرز")

    class Meta:
        db_table = "module_1_items"
        verbose_name = "مديول -1"
        verbose_name_plural = "مديول -1"
        ordering = ["sort_order", "name"]
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["code"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.code})"
