# Generated by Django 6.0.5 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب الفرز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قيمة تصنيف',
                'verbose_name_plural': 'قيم التصنيفات',
                'db_table': 'settings_lookups',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, default='', verbose_name='القيمة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('category', models.CharField(default='general', max_length=30, verbose_name='التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'settings_system',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='lookupcategory',
            index=models.Index(fields=['category', 'name'], name='settings_loo_categor_fb2e8a_idx'),
        ),
    ]
