# Generated by makemigrations for GDS-Template AuditLog model.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تحديث"),
                            ("delete", "حذف"),
                            ("login", "دخول"),
                            ("logout", "خروج"),
                            ("approve", "اعتماد"),
                            ("reject", "رفض"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="معرف الكائن",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="وصف الكائن",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="القيمة القديمة"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="القيمة الجديدة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإجراء"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_logs_user_idx",
                    ),
                    models.Index(
                        fields=["module", "-created_at"],
                        name="audit_logs_module_idx",
                    ),
                ],
            },
        ),
    ]
