# Generated by Django 6.0.5 on 2026-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_6193b2_idx',
            old_name='audit_logs_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_module_31f3f7_idx',
            old_name='audit_logs_module_idx',
        ),
        migrations.RenameIndex(
            model_name='lookupcategory',
            new_name='settings_lo_categor_7ff6b1_idx',
            old_name='settings_loo_categor_fb2e8a_idx',
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='category',
            field=models.CharField(help_text='مفتاح التصنيف (عام، يمكن تعريفه حسب المشروع)', max_length=100, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(default='general', help_text='مفتاح التصنيف (عام، يمكن تعريفه حسب المشروع)', max_length=30, verbose_name='التصنيف'),
        ),
    ]
