# Generated by Django 6.1.2 on 2026-10-06 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(db_index=True, max_length=40)),
                ('operation', models.CharField(max_length=10)),
                ('source_length', models.PositiveIntegerField(default=0)),
                ('result_length', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipher_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية تشفير',
                'verbose_name_plural': 'عمليات التشفير',
                'db_table': 'cipherlab_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
