# Generated by Django 6.0.5 on 2026-08-12 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module1Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(help_text='كود فريد يستخدم كمعرّف مرجعي', max_length=100, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب الفرز')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدّث بواسطة')),
            ],
            options={
                'verbose_name': 'مديول -1',
                'verbose_name_plural': 'مديول -1',
                'db_table': 'module_1_items',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='module_1_it_name_a300f2_idx'), models.Index(fields=['code'], name='module_1_it_code_3371b4_idx')],
            },
        ),
    ]
